"""update workflow idx

Revision ID: a8d01e382727
Revises: 675b5321501b
Create Date: 2024-09-24 09:05:28.589046

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d01e382727'
down_revision = '675b5321501b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow__conversation_variables_app_id_idx')
        batch_op.drop_index('workflow__conversation_variables_created_at_idx')
        batch_op.create_index(batch_op.f('workflow_conversation_variables_app_id_idx'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('workflow_conversation_variables_created_at_idx'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_created_at_idx'))
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_app_id_idx'))
        batch_op.create_index('workflow__conversation_variables_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('workflow__conversation_variables_app_id_idx', ['app_id'], unique=False)

    # ### end Alembic commands ###
