"""update global_docking_task table ligand_file_id to ligang_file_ids is list type

Revision ID: 8ca4fd88ba19
Revises: 75674abc7838
Create Date: 2024-10-16 06:24:04.142522

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca4fd88ba19'
down_revision = '75674abc7838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_docking_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ligand_file_ids', sa.ARRAY(sa.String(length=155)), nullable=True, comment='全局分子对接任务所需的ligand文件id数组，多个ligand文件以数组形式存储'))
        batch_op.drop_column('ligand_file_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_docking_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ligand_file_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True, comment='全局分子对接任务所需的ligand文件id'))
        batch_op.drop_column('ligand_file_ids')

    # ### end Alembic commands ###
