"""update molecular_docking_task table

Revision ID: f0469b547ffd
Revises: 81b5527acfb9
Create Date: 2024-10-14 05:19:13.727811

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0469b547ffd'
down_revision = '81b5527acfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecular_docking_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remove_ligand_file_id', sa.String(length=155), server_default='', nullable=False, comment='移除ligand小分子之后的pdb文件id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecular_docking_task', schema=None) as batch_op:
        batch_op.drop_column('remove_ligand_file_id')

    # ### end Alembic commands ###
