"""add global_docking_task table

Revision ID: 75674abc7838
Revises: d6cea5631f4f
Create Date: 2024-10-16 05:56:08.386394

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75674abc7838'
down_revision = 'd6cea5631f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_docking_task',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='全局分子对接的任务id'),
    sa.Column('fasta_file_id', sa.String(length=155), nullable=True, comment='全局分子对接任务所需的fasta文件id'),
    sa.Column('ligand_file_id', sa.String(length=155), nullable=True, comment='全局分子对接任务所需的ligand文件id'),
    sa.Column('out_pose_num', sa.Integer(), nullable=True, comment='全局分子对接任务的输出结果pose数量'),
    sa.Column('result', sa.Text(), nullable=True, comment='全局分子对接的结果'),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name='global_docking_task_pkey'),
    comment='全局分子对接任务结果数据表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_docking_task')
    # ### end Alembic commands ###
