"""add poseview table

Revision ID: a9003816517b
Revises: 8ca4fd88ba19
Create Date: 2024-11-04 06:46:32.844145

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9003816517b'
down_revision = '8ca4fd88ba19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_poseview_task',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='poseview的任务id'),
    sa.Column('receptor_file_id', sa.String(length=155), nullable=True, comment='poseview任务所需的receptor文件id'),
    sa.Column('ligand_file_ids', sa.ARRAY(sa.String(length=155)), nullable=True, comment='poseview任务所需的ligand文件id数组，多个ligand文件以数组形式存储'),
    sa.Column('result', sa.Text(), nullable=True, comment='poseview任务的结果'),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name='poseview_task_pkey'),
    comment='pose view 任务结果数据表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility_poseview_task')
    # ### end Alembic commands ###
