"""add sciminer_history_task table

Revision ID: 1a1a725a318a
Revises: f0469b547ffd
Create Date: 2024-10-14 09:18:08.558138

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1a725a318a'
down_revision = 'f0469b547ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sciminer_history_task',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='历史记录数据表id'),
    sa.Column('task_id', models.types.StringUUID(), nullable=False, comment='任务id'),
    sa.Column('task_name', sa.String(length=155), nullable=True, comment='任务名称'),
    sa.Column('label', sa.String(length=155), nullable=False, comment='任务类别标签'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='任务状态,默认等待中 PENDING，可选值：处理中 PROCESSING、成功 SUCCESS、失败 FAILURE'),
    sa.Column('created_by', models.types.StringUUID(), nullable=False, comment='创建人id'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name='sciminer_history_task_pkey')
    )
    with op.batch_alter_table('sciminer_history_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sciminer_history_task_created_by_idx'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('sciminer_history_task_label_idx'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('sciminer_history_task_task_id_idx'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('sciminer_history_task_task_name_idx'), ['task_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sciminer_history_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sciminer_history_task_task_name_idx'))
        batch_op.drop_index(batch_op.f('sciminer_history_task_task_id_idx'))
        batch_op.drop_index(batch_op.f('sciminer_history_task_label_idx'))
        batch_op.drop_index(batch_op.f('sciminer_history_task_created_by_idx'))

    op.drop_table('sciminer_history_task')
    # ### end Alembic commands ###
