"""update molecular_docking_task table

Revision ID: dcc2fc372936
Revises: 46e094547010
Create Date: 2024-09-26 06:17:59.200441

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcc2fc372936'
down_revision = '46e094547010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecular_docking_task', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP(0)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('molecular_docking_task', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP(0)'))

    # ### end Alembic commands ###
