"""update molecular_docking_task table

Revision ID: 95a32278428c
Revises: a8d01e382727
Create Date: 2024-09-26 05:44:47.919988

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a32278428c'
down_revision = 'a8d01e382727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecular_docking_task',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='分子对接的任务id'),
    sa.Column('task_name', sa.String(length=155), nullable=True, comment='分子对接任务名称'),
    sa.Column('pdb_file_id', sa.String(length=155), nullable=True, comment='分子对接任务所需的pdb文件id'),
    sa.Column('center_x', sa.Float(), nullable=True, comment='分子对接任务的中心点x坐标'),
    sa.Column('center_y', sa.Float(), nullable=True, comment='分子对接任务的中心点y坐标'),
    sa.Column('center_z', sa.Float(), nullable=True, comment='分子对接任务的中心点z坐标'),
    sa.Column('size_x', sa.Float(), nullable=True, comment='分子对接任务的大小x坐标'),
    sa.Column('size_y', sa.Float(), nullable=True, comment='分子对接任务的大小y坐标'),
    sa.Column('size_z', sa.Float(), nullable=True, comment='分子对接任务的大小z坐标'),
    sa.Column('ligand_file_ids', sa.ARRAY(sa.String(length=155)), nullable=True, comment='分子对接任务所需的ligand文件id数组，多个ligand文件以数组形式存储'),
    sa.Column('out_pose_num', sa.Integer(), nullable=True, comment='分子对接任务的输出结果pose数量'),
    sa.Column('result', sa.Text(), nullable=True, comment='分子对接的结果'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='分子对接的任务状态,默认等待中 PENDING，可选值：处理中 PROCESSING、成功 SUCCESS、失败 FAILURE'),
    sa.Column('created_by', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name='molecular_docking_task_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('molecular_docking_task')
    # ### end Alembic commands ###
